---
title: "Have ICT changed the game for mobility and migration?"
author: "Ana Cecila Montes and Ayra Rowena Reyla "
date: "11 December 2015"
output: pdf_document
bibliography: referencesreylamontes.bib
highlight: zenburn
theme: united
toc: yes
toc_depth: 3
---

#Abstract

---
\newpage







```{r setup, include=FALSE, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
#Clearing the workspace
#rm(list = ls(all=TRUE))

# 1. Loading packages
#install.packages("plm")
#install.packages("stargazer")
#install.packages("formula")

#library("ggmap")
#library("maptools")
#library("countrycode")
#library("RJSONIO")
#library("WDI")
#library("tidyr")
#library("rio")
#library("ggplot2")
#library("rworldmap")
#library("sp")
#library("Formula")
#library('plm')
#library("pglm")
#library("stargazer")
#library("migest")
#library("tseries")
#library("vif")

#2. Setting directory
#setwd('/Users/AnaCe/Desktop/Final_ProjectMontesReyla')
setwd('/Users/ayrarowenareyla/Desktop/Collaborative Social Sciences/Final_ProjectMontesReyla') 

#Merged <- read.csv(file="MontesandReyla")

#Set data as panel data
#Merged <- plm.data(Merged, index=c("iso2c", "year"))
```



# 1. Introduction
Migration is broadly defined as a permanent or semi-permanent relocation of residence, there are no restrictions placed upon the distance or voluntary or involuntary nature of moving [@Lee1966]. In fact, few countries today are not affected by international migration [@Martin2014] few countries today are  For many years, the idea of international migration meant disconnecting with one's homeland. This meant the process of communication with friends and family left behind was a slow process, often via hand written letters. However, since the dawn the digital age at the start of the 20th century information and communication technology (ICT) has radically changed the speed and nature of interactions between people worldwide. New ICT such as mobile phones have facilitated instant communication by phone calls, text messages, e-mail, and other social platforms. Cheap international telephone calls function as the 'social glue' binding migrants to their friends and families in their home country by creating constant involvement and engagement in their life [@Vetrovec2004]. @Castells2009 argues that the digital age has drastically changed the speed of communication within transnational populations. Since the introduction of the Internet to the masses, it has developed into a globally diverse web of opportunities for gathering information, interacting globally and effectively producing new forms of media and content for consumption. 

Presently, the digital era has transformed how people live their lives, how they interact with one another and how they learn and gather new information. There is no doubt that ICT have had a monumental impact on the world in which we live, fundamentally changing the way individuals communicate, entertain and learn. With the increase accessibility to ICTs and the existing state of mobility between people around the world, it is easy to envision an existing relationship between increased access to communication and information and the results of migration. Social media developed on the Internet has become one of the most popular channels of communication. These new communication devices created by the Internet and mobile phones are important for migrants who frequently remain in contact with friends of family members in their original locations. New innovation in digital technologies allows people to thing beyond borders and it is reinforced by both digital and societal developments [@Castells2010]. 

Furthermore, with the advent of ICT in all components of everyday life, it is important and yet interesting to observe the how the relationship between ICT and migration has developed. This empirical analysis seeks to observe if the increase use of technologies such as the Internet and mobile phones impacted the flow of emigration? With the beginning of globalization, we aim to observe the changes in the context of migration around the world. One driving factor increasingly put forward in recent years is the use of technology. According to @Hiller2004, computer mediated communication has created new possibilities for migrants to maintain strong linkages and ties with their home nations. Not only has new technology improved and heightened communication, it has also bridged cultural gap between countries as it allows people to easily gathering new information and knowledge about other cultures. This of course has made a large impact on people's perception on other cultures and their worldviews. Overall, technology has changed the landscape for communicating, and gathering knowledge and information. These revolutions that have transformed society are making travel and telecommunications cheaper and easier than ever. Moreover, Technology has enhanced the aspects of interaction as it is transforming the way individuals communicate.  

As such, this paper will be organized as follows. Section 2 will provide a theoretical foundation for the analysis, as to set the scene for subsequent discussion. Section 3 will be a literature review to identify the converging ideas and understand contemporary studies on the topic. Section 4 will provide the basis for our empirical analysis, by explaining the data and methodology. Section 5 will provide the results of the analysis, followed by a discussion. 



# 3. Understanding Migration: A Theoretical Foundation
Migration is one of the three main determinants of a country's population development [@Lee1966]. Every act of migration involves an origin, a destination and intervening set of obstacles and opportunities. The idea of human mobility is that individuals are always in constant circulation. Humans are constantly moving throughout their lives, which could be seen on varying degrees. Whether it is a college student returning home every summer, or a family permanently moving to another country. In existing literature, the factors that influence an individual's decision to migrate, more specifically to emigrate from their origin country to another location are multifold and are described as a combination of social, ethnic, and politically related factors that can be categorized as either Push or Pull factors that are divided into three categories: Economic and demographic, political, and social and cultural [@Gold2013].

Push factors are reasons that are generally forced and negative. In particular, these factors are associated with the country of origin. When considering the three categories, people are 'pushed' to leave their homeland for a number of varying reasons. Social push factors include discrimination, for example, those facing religious or racial discrimination will be negatively influenced to leave their country of origin to seek a new location that does not have leave them socially oppressed. Also, political push factors play a role as to why people leave. Often people living in countries with on going war, conflict, government instability or corruption are forced to flee to avoid harm. Furthermore, economic push factors play a large role in emigration. Countries with low unemployment, rampant poverty or a high cost of living may force individuals to seek more reasonable and opportunistic locations to settle.  Moreover, people will move for more employment opportunities

Pull factors on the other hand are the positive traits that positively affect the movement of people. Often people are drawn to move to places to escape the negative factors pushing them out. To escape the issue of social discrimination, people are pulled to countries with high levels of personal freedom or equality. Migrants seeking alleviation from political push factors will be drawn to locations with well-established individual rights or a well functioning justice system. Moreover, people will move to find more economically stable reasons such as employment opportunities or high standard of living.

Another theory common among the literature is the _Neo-classical theory_, which affirms that the market allocates labor depending on demand and supply. In most cases, the demand of employment will automatically provide a supply of persons willing to do the labor in order for the market to reach equilibrium. The determinants of the individual decision will be based on the wage differentials among two geographical areas. To illustrate, a person will be more willing to move to another for labor and employment if the offering wage is higher and more competitive than in their home market. 



| Motivations for migration  | Push factors                       | Pull factors                             |
| -------------------------- | -----------------------------------|------------------------------------------|
| `Economic and demographic` | Poverty                            | Prospects of higher wages                |
|                            | Unemployment                       | Potential for improved standard of living|
|                            | Low wages                          | Personal or professional development     |
|                            | High fertility rates               |                                          |
|                            | Lack of basic health and education |                                          |
| `Political`                | Conflict, insecurity, violence     | Safety and security                      |
|                            | Poor governance                    | Political freedom                        |
|                            | Corruption                         |                                          |
|                            | Human rights abuses                |                                          |
| `Social and cultural`      | Discrimination based               | Family reunification                     |
|                            | on ethnicity, gender,              | Ethnic (diaspora migration) homeland     |
|                            | religion                           | Freedom from discrimination              |

***Source:*** The World Bank retrived from @Table1


# 4. ICT as a Determinant 

ICT plays an important role in many stages of the migration process. Wood also argues that different modes of communicating information such as news, films and advertisments are important sources of information for people considering miration @Wood2001. Moreover, new ICT may have created the image of wealth and prosperity of more developed countries in those living in developing regions [@Hamel2009]. Information is crucial in the final decision making process of migration. However, this information flows both ways. Simultaneously, accessability to ICT have fostered a negative perception of migrants [@Wood2001]. Castells argues that being interconnected through a 'network society' has changed the nature of international migration, ICT has increased the rate at which people gather information and communication transnationally [@Castells2010].Additionally,[@Vetrovec2004] argued that the reduction of the cost of communication has drastically changed how information is collected and percieved. Similarly, mobile phone technologies have made information and knowledge more readily accessoble, thus creating realistic and more informed expectations for potential migrants [@PanagakosandHorst2006]. 

@Castells2009 argues of a new 'network society' where information is made a valuable resource through ICT. Technology allows for information to flow quickly and efficiently, providing opportunities for people to interact with one another [@Barney2004]. Migration is increasing in spite of more restricted boarder controls because of the development of "networks of connectivity" between societies through channels like the Internet, which offer opportunities for the an expansion of information [@Castells2010]. Being connected online offers perpetual connectivity and allows individuals to foster a 'network' outside and within the borders of their origin country. Information constitutes a core of the social process associated with migration. The circulation of information through networks creates 'strong ties' [@Granovetter1983]. 

Another relevant theory associated with the focus of this analysis is _Globalization theory_. According to @Castles2014, Globalization can be defined as as the process in which world wide interconnections have not only expanded but have deepened the speed of connectivity, and time of all aspects of social life. This theory suggest that globalization has very inconclusive effects on migration flows. On one hand, globalization has strengthened migration since it has fostered new developments in transport and comunications. However, on the other hand, it is argued that  these new developments have also changed the way in which people work and interact with each other. For example, it has increased outsourcing, commuting and teleworking. Although it sounds like a positive innovation, this has also made migration to another location less attractive, as all the resources are so readily available. 


# 5 Method
## 5.1 Data Selection

In order to examine the flows of migration, this analysis uses data from the _International Migrant Stock_ produced by the United Nations. The data contains information from 232 countries and provides the number of migrants by destination and country of origin for four periods of time; 1990, 2000, 2010, and 2013. Moreover, to account for technology diffusion we will use _World Bank indicators_ on the number of Internet users and the number of cellular mobile subscriptions for each country. 

The _International Migrant Stock Total_ indicates the number of people born in a country other than the country in which they currently reside in, this includes refugees as well. The data set estimates the international migrant stock at a particular time and are mainly collect from population censuses. 
Also, the data set presents the estimates of : (1) international migrant stock at mid-year; (2) total population at mid-year (thousands); (3) international migrant stock as a percentage of the total population; (4) annual rate of change of migrant stock (percentage); and (5) estimated number of refugees. The estimates are based on official statistics on the foreign-born or the foreign population. 

This analysis will focus on the estimates for the years 1990, 2000, 2010 and 2013. 

Additionally, in order to conduct a more thorough analysis we will include a number of aggregate data collected from _The World Bank indicators_. There are many other determinants of migration, that is why this analysis chooses to include a wide variety of World Bank indicators. The chosen indicators are used to measure certain push factors. 

To measure economic and demographic determinants this analysis includes the _fertility rate_ indicator. Indicators such as _poverty_ and _unemployment_ have been removed from the analysis, as there are many missing values in the data set. 


## 5.1 Data Selection
In order to examine the flows of migration, we intend to use data on trends in _International Migrant Stock_ produced by the United Nations. The data contains information from 232 countries and provides the number of migrants by destination and country of origin for four periods of time; 1990, 2000, 2010, and 2013. Moreover, to account for technology diffusion we will use _World Bank indicators_ on the number of Internet users and the number of cellular mobile subscriptions for each country. 

##5.2 Emperical Strategy

To examine the hypothesized effect of technology, cross country panel data analysis will be conducted. Our dependent variable of interest is the total number of immigrants by country, this will be our Y and the independent variable (X) we will be stuyding are number of internet users, and the number of mobile users per country. The countrol variables we plan on using include, wage differentials, economic growth, unemployment, criminal death rate, conflict and political freedoms. This research will use panel data methods to address the research question, this includes panel data regression, fixed effects and random effects. 


# 6 Limitations

One of the major limitations on migration studies is the difficulty of accessing good and reliable datasets. The United Nations (UN) have complied a large amount of statistical evidence on the topic of migration, however, the database does not have a large number of year observations. This will limit the resarch because the results will not yield year to year analysis, which of course will rely mostly on between country effects. 



#References









